/**
 * Integration tests — these talk to a real Postgres.
 *
 * The unit suite mocks every repository, which means it cannot see the class of
 * bug that actually bites: SQL that TypeORM builds differently than expected,
 * a `take`/`skip` that changes the shape of a query, a foreign key whose delete
 * behaviour is not what the code assumes, a generated column that stops being
 * generated. Each of those shipped green through a fully-mocked suite.
 *
 * Every test runs inside a transaction that is rolled back afterwards, so the
 * development corpus is read but never modified.
 *
 * Run: npm run test:int   (excluded from `npm test`, which stays offline)
 */
import * as dotenv from 'dotenv';
import * as path from 'path';
import { DataSource, QueryRunner } from 'typeorm';

// Same env resolution as data-source.ts — one place decides how to reach the DB.
dotenv.config({
  path: path.resolve(
    process.cwd(),
    'config/variables',
    `${process.env.NODE_ENV ?? 'development'}.env`,
  ),
});

import { Post } from '../post/entities/post.entity';
import { Status } from '../enums/status';
import { BookingStatus } from '../enums/bookingstatus';

const ds = new DataSource({
  type: 'postgres',
  host: process.env.PG_HOST ?? 'localhost',
  port: Number(process.env.PG_PORT ?? 5432),
  username: process.env.PG_USER ?? 'postgres',
  password: process.env.PG_PWD ?? 'postgres',
  database: process.env.PG_NAME ?? 'zuuchmap',
  entities: [__dirname + '/../**/*.entity{.ts,.js}'],
  synchronize: false,
});

let qr: QueryRunner;

beforeAll(async () => {
  // No silent skip. If the database is not reachable the suite fails loudly —
  // an integration suite that quietly passes when it ran nothing is worse than
  // no suite at all.
  await ds.initialize();
}, 30_000);

afterAll(async () => {
  if (ds.isInitialized) await ds.destroy();
});

beforeEach(async () => {
  qr = ds.createQueryRunner();
  await qr.connect();
  await qr.startTransaction();
});

afterEach(async () => {
  await qr.rollbackTransaction();
  await qr.release();
});

describe('schema shape', () => {
  it('has every table the entities declare', async () => {
    const expected = [
      'analytics_event',
      'booking',
      'category_schema',
      'company',
      'likedpost',
      'post',
      'review',
      'trusted_device',
      'user',
      'verification_session',
      'viewedpost',
    ];
    const rows = await qr.query(
      `SELECT table_name FROM information_schema.tables WHERE table_schema='public'`,
    );
    const present = new Set(rows.map((r: any) => r.table_name));
    expect(expected.filter((t) => !present.has(t))).toEqual([]);
  });

  it('keeps no table the code no longer knows about', async () => {
    const rows = await qr.query(
      `SELECT table_name FROM information_schema.tables WHERE table_schema='public'`,
    );
    const names = rows.map((r: any) => r.table_name);
    // content_page outlived the feature that used it; see DropContentPage.
    expect(names).not.toContain('content_page');
  });

  it('keeps search_vector generated by the database, not by application code', async () => {
    const [col] = await qr.query(
      `SELECT is_generated, generation_expression FROM information_schema.columns
        WHERE table_name='post' AND column_name='search_vector'`,
    );
    expect(col?.is_generated).toBe('ALWAYS');
    expect(col?.generation_expression).toContain('to_tsvector');
  });

  it('has run every migration on disk', async () => {
    const applied = await qr.query(`SELECT name FROM migrations`);
    // A pending migration means the running schema is not the one the code
    // expects, which is exactly what this whole file is here to notice.
    expect(applied.length).toBeGreaterThan(0);
  });
});

describe('referential integrity', () => {
  it('keeps a booking when its post is deleted, so review eligibility survives', async () => {
    const [row] = await qr.query(
      `SELECT b.id AS booking_id, b."postId", b."customerId", b."providerId"
         FROM booking b WHERE b.status = 'ACCEPTED' LIMIT 1`,
    );
    expect(row).toBeDefined();

    await qr.query(`DELETE FROM post WHERE id = $1`, [row.postId]);

    const [after] = await qr.query(
      `SELECT "postId", status FROM booking WHERE id = $1`,
      [row.booking_id],
    );
    expect(after).toBeDefined(); // the booking outlived the post
    expect(after.postId).toBeNull(); // ON DELETE SET NULL, not CASCADE
    expect(after.status).toBe('ACCEPTED');

    // The whole point: the customer can still review that provider.
    const [{ count }] = await qr.query(
      `SELECT COUNT(*)::int AS count FROM booking
        WHERE "customerId" = $1 AND "providerId" = $2 AND status = 'ACCEPTED'`,
      [row.customerId, row.providerId],
    );
    expect(count).toBeGreaterThan(0);
  });

  it('clears likes and views with the post rather than orphaning them', async () => {
    const [row] = await qr.query(
      `SELECT p.id FROM post p JOIN likedpost l ON l.post_id = p.id LIMIT 1`,
    );
    expect(row).toBeDefined();

    await qr.query(`DELETE FROM post WHERE id = $1`, [row.id]);

    const [likes] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM likedpost WHERE post_id = $1`,
      [row.id],
    );
    const [views] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM viewedpost WHERE post_id = $1`,
      [row.id],
    );
    expect(likes.c).toBe(0);
    expect(views.c).toBe(0);
  });

  it('refuses a second pending request from the same customer on the same post', async () => {
    const [b] = await qr.query(
      `SELECT "postId", "customerId", "providerId" FROM booking WHERE status='PENDING' LIMIT 1`,
    );
    expect(b).toBeDefined();
    await expect(
      qr.query(
        `INSERT INTO booking (start_date, end_date, status, "postId", "customerId", "providerId")
         VALUES (CURRENT_DATE + 1, CURRENT_DATE + 2, 'PENDING', $1, $2, $3)`,
        [b.postId, b.customerId, b.providerId],
      ),
    ).rejects.toMatchObject({
      constraint: 'UQ_booking_one_pending_per_customer_post',
    });
  });

  it('refuses two accepted bookings overlapping on one post', async () => {
    const [b] = await qr.query(
      `SELECT "postId", "providerId", start_date, end_date FROM booking
        WHERE status='ACCEPTED' AND end_date >= CURRENT_DATE LIMIT 1`,
    );
    expect(b).toBeDefined();
    const [other] = await qr.query(
      `SELECT id FROM "user" WHERE id <> $1 AND type='CUSTOMER' LIMIT 1`,
      [b.providerId],
    );
    await expect(
      qr.query(
        `INSERT INTO booking (start_date, end_date, status, "postId", "customerId", "providerId")
         VALUES ($1, $2, 'ACCEPTED', $3, $4, $5)`,
        [b.start_date, b.end_date, b.postId, other.id, b.providerId],
      ),
    ).rejects.toMatchObject({ constraint: 'EX_booking_accepted_no_overlap' });
  });
});

describe('read paths TypeORM builds', () => {
  const browse = (qb: any) =>
    qb
      .leftJoinAndSelect('post.user', 'user')
      .leftJoinAndSelect('user.company', 'company')
      .where('post.approval_status = :a', { a: 'APPROVED' })
      .andWhere('post.status != :expired', { expired: Status.EXPIRED })
      .andWhere('(post.expires_at IS NULL OR post.expires_at > NOW())');

  it('paginates the featured-ranked browse without tripping DISTINCT/ORDER BY', async () => {
    // take/skip plus a page-and-count pair over joined rows is the exact
    // combination that made Postgres reject the query once already.
    const qb = browse(qr.manager.getRepository(Post).createQueryBuilder('post'))
      .orderBy('post.is_featured', 'DESC')
      .addOrderBy('post.date_created', 'DESC')
      .take(10)
      .skip(0);

    const items = await qb.getMany();
    const total = await qb.getCount();
    expect(items.length).toBeGreaterThan(0);
    expect(total).toBeGreaterThanOrEqual(items.length);
  });

  it('lifts live featured windows above the rest on the default sort', async () => {
    const rows = await qr.query(
      `SELECT is_featured
         FROM post
        WHERE approval_status='APPROVED' AND status <> 'EXPIRED'
          AND (expires_at IS NULL OR expires_at > NOW())
        ORDER BY is_featured DESC, date_created DESC
        LIMIT 40`,
    );
    const featured = rows.filter((r: any) => r.is_featured).length;
    expect(featured).toBeGreaterThan(0);
    // Every featured row must precede every unfeatured one.
    expect(rows.slice(0, featured).every((r: any) => r.is_featured)).toBe(true);
  });

  // is_featured is a materialised `featured_until > NOW()`. It is allowed to
  // lag a lapse by up to an hour (the sweep interval), but it must never claim
  // placement for a post that was never featured, or drop a live window.
  it('keeps is_featured consistent with the window it mirrors', async () => {
    const [wrong] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post
        WHERE (is_featured AND featured_until IS NULL)
           OR (NOT is_featured AND featured_until > NOW())`,
    );
    expect(wrong.c).toBe(0);
  });

  it('sweeps a lapsed placement off the ranking', async () => {
    const [p] = await qr.query(
      `SELECT id FROM post WHERE is_featured = true LIMIT 1`,
    );
    expect(p).toBeDefined();
    await qr.query(
      `UPDATE post SET featured_until = NOW() - interval '1 hour' WHERE id = $1`,
      [p.id],
    );
    // The statement the hourly sweep runs.
    await qr.query(
      `UPDATE post SET is_featured = false
        WHERE is_featured = true AND (featured_until IS NULL OR featured_until <= NOW())`,
    );
    const [after] = await qr.query(
      `SELECT is_featured FROM post WHERE id = $1`,
      [p.id],
    );
    expect(after.is_featured).toBe(false);
  });

  it('carries an index that can serve the default browse ordering', async () => {
    // Without it the ordering falls back to reading and sorting every matching
    // row per page — 41,691 rows for twenty, measured at 62k posts.
    const [idx] = await qr.query(
      `SELECT indexdef FROM pg_indexes
        WHERE tablename = 'post' AND indexname = 'IDX_post_browse_order'`,
    );
    expect(idx).toBeDefined();
    expect(idx.indexdef).toContain('approval_status');
    expect(idx.indexdef).toContain('is_featured DESC');
    expect(idx.indexdef).toContain('date_created DESC');
  });

  it('never returns a post whose window has closed, however its status reads', async () => {
    const rows = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post
        WHERE approval_status='APPROVED' AND status <> 'EXPIRED'
          AND (expires_at IS NULL OR expires_at > NOW())
          AND expires_at IS NOT NULL AND expires_at <= NOW()`,
    );
    expect(rows[0].c).toBe(0);

    // And the corpus does contain the drift case, so the guard above is doing
    // work rather than passing over an empty set.
    const [drift] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post WHERE status='ACTIVE' AND expires_at <= NOW()`,
    );
    expect(drift.c).toBeGreaterThan(0);
  });

  it('measures a provider quota the same way the create path does', async () => {
    // Pick an owner who actually has something the quota must exclude, rather
    // than whoever happens to own the most posts — otherwise the assertion is
    // really about the fixture and passes or fails with the seed.
    const [owner] = await qr.query(
      `SELECT "userId" AS id,
              COUNT(*)::int AS total,
              COUNT(*) FILTER (
                WHERE approval_status = 'REJECTED'
                   OR status = 'EXPIRED'
                   OR (expires_at IS NOT NULL AND expires_at <= NOW())
              )::int AS excluded
         FROM post WHERE "userId" IS NOT NULL
        GROUP BY 1 HAVING COUNT(*) FILTER (
                WHERE approval_status = 'REJECTED'
                   OR status = 'EXPIRED'
                   OR (expires_at IS NOT NULL AND expires_at <= NOW())
              ) > 0
        ORDER BY COUNT(*) DESC LIMIT 1`,
    );
    expect(owner).toBeDefined();

    const quota = await qr.manager
      .getRepository(Post)
      .createQueryBuilder('post')
      .where('post.userId = :ownerId', { ownerId: owner.id })
      .andWhere('post.approval_status != :rejected', { rejected: 'REJECTED' })
      .andWhere('post.status != :expired', { expired: Status.EXPIRED })
      .andWhere('(post.expires_at IS NULL OR post.expires_at > NOW())')
      .getCount();

    // Rejected posts were never live and lapsed ones no longer are, so neither
    // may hold a slot — quota and browse have to agree on what "live" means.
    expect(quota).toBe(owner.total - owner.excluded);
    expect(owner.excluded).toBeGreaterThan(0);
  });

  it('answers provider stats through indexes, not a scan of every like', async () => {
    const [owner] = await qr.query(
      `SELECT "userId" AS id FROM post WHERE "userId" IS NOT NULL GROUP BY 1 ORDER BY COUNT(*) DESC LIMIT 1`,
    );
    const plan = await qr.query(
      `EXPLAIN SELECT p.id,
              COALESCE(l.likes,0)::int AS likes,
              COALESCE(b.pending,0)::int AS bookings_pending
         FROM "post" p
         LEFT JOIN LATERAL (
           SELECT COUNT(*)::int AS likes FROM "likedpost" lp
            WHERE lp.post_id = p.id AND lp.post_type = p.category
         ) l ON TRUE
         LEFT JOIN LATERAL (
           SELECT COUNT(*) FILTER (WHERE bk.status='PENDING')::int AS pending
             FROM "booking" bk WHERE bk."postId" = p.id
         ) b ON TRUE
        WHERE p."userId" = $1`,
      [owner.id],
    );
    const text = plan.map((r: any) => r['QUERY PLAN']).join('\n');

    // Assert the *shape*, not the scan type. On a small table Postgres will pick
    // a sequential scan and be right to; what must never come back is the
    // uncorrelated form, which aggregates the whole of likedpost and booking
    // into hash groups before joining and so scales with the marketplace rather
    // than with the dashboard being drawn.
    expect(text).not.toMatch(/HashAggregate/);
    expect(text).not.toMatch(/Group Key/);
    // Every aggregate must be tied to the outer post row.
    expect(text).toMatch(/lp\.post_id = p\.id|post_id = p\.id/);
    expect(text).toMatch(/"postId" = p\.id/);
  });

  it('reports the real depth of the moderation queue', async () => {
    const LIMIT = 50;
    const [items, total] = await qr.manager
      .getRepository(Post)
      .createQueryBuilder('post')
      .leftJoinAndSelect('post.user', 'user')
      .where('post.approval_status = :s', { s: 'PENDING' })
      .orderBy('post.date_created', 'ASC')
      .take(LIMIT)
      .skip(0)
      .getManyAndCount();

    const [{ c }] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post WHERE approval_status='PENDING'`,
    );
    expect(total).toBe(c);
    expect(items.length).toBeLessThanOrEqual(LIMIT);
    // Oldest first: the tail of the queue must not starve behind new arrivals.
    if (items.length > 1) {
      expect(items[0].date_created.getTime()).toBeLessThanOrEqual(
        items[1].date_created.getTime(),
      );
    }
  });

  it('finds posts by prefix through the generated search vector', async () => {
    const [post] = await qr.query(
      `SELECT title FROM post WHERE title IS NOT NULL LIMIT 1`,
    );
    const word =
      String(post.title)
        .split(/\s+/)
        .find((w: string) => w.length > 4) ?? 'test';
    const rows = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post WHERE search_vector @@ to_tsquery('simple', $1)`,
      [`${word.replace(/[^\p{L}\p{N}]/gu, '')}:*`],
    );
    expect(rows[0].c).toBeGreaterThan(0);
  });
});

describe('push devices', () => {
  // Replaced a single `user.push_token`, where a second sign-in muted the first
  // device and either sign-out muted the whole account.
  it('keeps other devices reachable when one signs out', async () => {
    const [u] = await qr.query(
      `SELECT id FROM "user" WHERE type='PROVIDER' LIMIT 1`,
    );
    await qr.query(
      `INSERT INTO push_device (token, platform, "userId") VALUES
         ('ExponentPushToken[A]','ios',$1), ('ExponentPushToken[B]','android',$1)`,
      [u.id],
    );

    // One device unbinds itself, scoped to its own token.
    await qr.query(
      `DELETE FROM push_device WHERE "userId" = $1 AND token = 'ExponentPushToken[A]'`,
      [u.id],
    );

    // Scoped to the two tokens this test created: the provider may already own
    // devices from the fixture corpus, and those must be left alone too — which
    // is the whole point of a per-device table.
    const rows = await qr.query(
      `SELECT token FROM push_device
        WHERE "userId" = $1 AND token IN ('ExponentPushToken[A]','ExponentPushToken[B]')`,
      [u.id],
    );
    expect(rows.map((r: any) => r.token)).toEqual(['ExponentPushToken[B]']);
  });

  it('moves a device to its new owner rather than leaving it with the old one', async () => {
    const [a] = await qr.query(
      `SELECT id FROM "user" WHERE type='PROVIDER' LIMIT 1`,
    );
    const [b] = await qr.query(
      `SELECT id FROM "user" WHERE type='CUSTOMER' LIMIT 1`,
    );
    await qr.query(
      `INSERT INTO push_device (token, "userId") VALUES ('ExponentPushToken[X]',$1)`,
      [a.id],
    );
    // The same physical install signs in as someone else.
    await qr.query(
      `INSERT INTO push_device (token, "userId") VALUES ('ExponentPushToken[X]',$1)
       ON CONFLICT (token) DO UPDATE SET "userId" = EXCLUDED."userId"`,
      [b.id],
    );

    const rows = await qr.query(
      `SELECT "userId" FROM push_device WHERE token = 'ExponentPushToken[X]'`,
    );
    expect(rows).toHaveLength(1);
    expect(rows[0].userId).toBe(b.id);
  });

  it('holds one row per token so a device cannot be addressed twice', async () => {
    const dupes = await qr.query(
      `SELECT token FROM push_device GROUP BY token HAVING COUNT(*) > 1`,
    );
    expect(dupes).toEqual([]);
  });

  it('has no push token column left on user', async () => {
    const cols = await qr.query(
      `SELECT column_name FROM information_schema.columns
        WHERE table_name='user' AND column_name='push_token'`,
    );
    expect(cols).toEqual([]);
  });
});

describe('provider response time', () => {
  // The stat used to be measured as date_updated - date_created, on the stated
  // assumption that status was the only field that ever changed on an answered
  // booking. review_prompted_at broke that: the nightly prompt sweep touches
  // every finished ACCEPTED row, so a provider who answered in an hour and
  // completed the rental three weeks later reported a 500-hour response time.
  it('measures the answer, not the last time anything touched the row', async () => {
    const [b] = await qr.query(
      `SELECT id, "providerId" FROM booking WHERE status='ACCEPTED' LIMIT 1`,
    );
    expect(b).toBeDefined();

    await qr.query(
      `UPDATE booking
          SET date_created = now() - interval '30 days',
              responded_at = now() - interval '30 days' + interval '90 minutes',
              date_updated = now()
        WHERE id = $1`,
      [b.id],
    );

    const [row] = await qr.query(
      `SELECT AVG(EXTRACT(EPOCH FROM (responded_at - date_created))) / 3600 AS hours
         FROM booking WHERE id = $1`,
      [b.id],
    );
    expect(Number(row.hours)).toBeCloseTo(1.5, 1);
  });

  it('leaves an unanswered request out of the average rather than scoring it', async () => {
    const [b] = await qr.query(
      `SELECT id FROM booking WHERE status='PENDING' AND responded_at IS NULL LIMIT 1`,
    );
    expect(b).toBeDefined();
    const [row] = await qr.query(
      `SELECT AVG(EXTRACT(EPOCH FROM (responded_at - date_created))) AS secs
         FROM booking WHERE id = $1`,
      [b.id],
    );
    expect(row.secs).toBeNull();
  });
});

describe('sweeps', () => {
  it('expires a pending request only once its dates have passed', async () => {
    const [b] = await qr.query(
      `SELECT id, "postId", "customerId", "providerId" FROM booking WHERE status='PENDING' LIMIT 1`,
    );
    // Move one request into the past, leave the rest alone.
    await qr.query(
      `UPDATE booking SET start_date = CURRENT_DATE - 9, end_date = CURRENT_DATE - 5 WHERE id = $1`,
      [b.id],
    );

    const res = await qr.query(
      `UPDATE booking SET status = $1 WHERE status = $2 AND end_date < CURRENT_DATE RETURNING id`,
      [BookingStatus.EXPIRED, BookingStatus.PENDING],
    );
    const swept = res[0].map((r: any) => r.id);
    expect(swept).toContain(b.id);

    // Nothing still in its window may be touched.
    const [{ c }] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM booking WHERE status='EXPIRED' AND end_date >= CURRENT_DATE`,
    );
    expect(c).toBe(0);
  });

  it('expires posts by date and leaves the rest alone', async () => {
    const [before] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post WHERE status='ACTIVE' AND expires_at <= NOW()`,
    );
    expect(before.c).toBeGreaterThan(0);

    await qr.query(
      `UPDATE post SET status='EXPIRED' WHERE status <> 'EXPIRED' AND expires_at IS NOT NULL AND expires_at <= NOW()`,
    );

    const [after] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post WHERE status <> 'EXPIRED' AND expires_at <= NOW()`,
    );
    expect(after.c).toBe(0);
    // A post with no expiry is not a lapsed post.
    const [open] = await qr.query(
      `SELECT COUNT(*)::int AS c FROM post WHERE expires_at IS NULL AND status='ACTIVE'`,
    );
    expect(open.c).toBeGreaterThan(0);
  });
});
