export enum District {
    BAGANUUR = 'BAGANUUR',
    BAGAKHANGAI = 'BAGAKHANGAI',
    BAYANGOL = 'BAYANGOL',
    BAYANZURKH = 'BAYANZURKH',
    NALAIKH = 'NALAIKH',
    SONGINOKHAIRKHAN = 'SONGINOKHAIRKHAN',
    SUKHBAATAR = 'SUKHBAATAR',
    KHANUUL = 'KHANUUL',
    CHINGELTEI = 'CHINGELTEI'
}